pipeline {
  agent any

  stages {

    stage('Pull Image') {
      steps {
        sh 'docker pull jmanishankar/nginxbirth'
      }
    }

    stage('Stop Old Container (if exists)') {
      steps {
        sh '''
        docker rm -f nginxbirth-container || true
        '''
      }
    }

    stage('Run Container') {
      steps {
        sh '''
        docker run -d \
        --name alc-jenkins-pipeline \
        -p 80:80 \
        jmanishankar/nginxbirth
        '''
      }
    }

    stage('Verify') {
      steps {
        sh 'docker ps'
      }
    }
  }
}
